#
# update configuration file
#
metrics:
  # list of couples with metric: metric name and coef: double
  # - at least one quality metric
  # - at least one cost metric
  # - sum of coefs for quality metrics must be 1
  - metric: CVE
    # coef: 0.6
    coef: 0.0
  - metric: FRESHNESS
    # coef: 0.2
    coef: 1.0 # just focus on FRESHNESS when updating
  - metric: POPULARITY_1_YEAR
    # coef: 0.2
    coef: 0.0
  - metric: COST
    # coef: 0.5
    coef: 0.0 # COST_LIMIT is 0.0
constraints:
  # list (possibly empty) of constraints with constraint: and value:
  # a constraint can be one of:
  # - constraint: COST_LIMIT and value: double -> maximum value of total cost of solution (not used if COST is not part of the metrics)
  # - constraint: CVE_LIMIT and value: double -> maximum value of total CVE of solution (not used if CVE is not part of the metrics)
  # - constraint: PRESENCE and value: some id -> id must be present in solution
  # - constraint: ABSENCE and value: some id -> id must be absent in solution
  # notes:
  # - if you use both PRESENCE and ABSENCE for some same id, there is no solution
  # - if you use COST_LIMIT and no solution exist under this limit, there is no solution
  - constraint: COST_LIMIT
    value: 0.0 # COST must be zero
  # - constraint: CVE_LIMIT
  #   value: 0.0
  # - constraint: PRESENCE
  #   value: "group:artifact:version"
  # - constraint: ABSENCE
  #   value: "groupe:artifact:version"
releases:
  # either NONE, LOCAL (default), CONSTRAINTS(NONE + all releases of libs in ABSENCE & PRESENCE), LOCAL_AND_CONSTRAINTS (LOCAL + all libs of releases in ABSENCE), or GLOBAL
  # focus: LOCAL
  focus: GLOBAL
  # combination of MORE_RECENT, NO_PATCHES
  # can be empty to select all, default is [MORE_RECENT]
  # (!!) by now only [MORE_RECENT] is supported (others -> [MORE_RECENT])
  selectors: [MORE_RECENT]
costs:
  # either NONE, LOCAL (default), CONSTRAINTS, LOCAL_AND_CONSTRAINTS, or GLOBAL
  # focus: LOCAL
  focus: GLOBAL
  # default value for NONE or unknown costs, MAX or MIN
  default: MAX
  # tool used to compute costs at LOCAL level, either NONE or MARACAS (default)
  tool-direct: MARACAS
  # tool used to compute costs at non-root level, either NONE (default) or JAPICMP
  # tool-indirect: NONE
  tool-indirect: JAPICMP